
browser.name = chrome

base.url = https://example.com

dropdown.type = text

screenshot.dir = test-output/screenshots

full.name = Tony stark

email.id = lakshmi@xooper.com

company.name = Genriches

phone.no = 9876543210

password = password12

confirm.password = password12

O.T.P = 123456

job.role = Software Developer

job.skills = Java, Selenium, Git, TestNG

job.location =Chennai

job.type = Hybrid

employement.type = Full-time

min_experience = 3

max_experience = 8

industry_type = QA

language.preference = English

tone = Professional

job_description = We seeking for strong QA Automation Engineer with good hands on experience










